### ISSUE TITLE
WIP: Revamp UI

### ISSUE THREAD

**Issue by CleoMenezesJr** [CleoMenezesJr/auto-activities#17]
I am working to modernize the extension interface with Libadwaita widgets. I would like to know if this change interests you, so I can proceed with the change.

![image](https://user-images.githubusercontent.com/54215258/193935645-58171608-43e2-4d14-a50c-cffc9d7eafab.png)

**Comment by jan-senaa** [comment]
I'm sorry for the late response, I was away for quite some time.

It's fine by me of course. If you're still interested, I would like to see it.

**Comment by CleoMenezesJr** [comment]
Cool, I'll start doing that. I was thinking, you had said that you no longer used gnome and wondered if there is a possibility that you may transfer the extension for me to maintain it (just if you really don't want to keep it).

**Comment by jan-senaa** [comment]
Well, it seems like I'm not going to return to GNOME soon. And I don't really care about this extension that much anymore. If you want to keep maintaining it, I would be really happy.

**Comment by jan-senaa** [comment]
Please notify me when you are ready to transfer (after you delete the fork), and I'll make a repo transfer request. I'll also delete the GNOME Extensions page on web for you to upload your version.

**Comment by CleoMenezesJr** [comment]
Right, I already deleted the fork.

**Comment by jan-senaa** [comment]
Transferred :tada:

I'll delete the extension webpage as well so you can upload the next version with the new uuid and stuff.

**Comment by CleoMenezesJr** [comment]
Thank you very much and sorry to bother you at some point. I hope to keep maintaining it for a long time and do not worry that you will always be mentioned as an extension creator.
