### ISSUE TITLE
[Feature Request] Option to disable entering empty workspaces 

### ISSUE THREAD

**Issue by 13hannes11** [CleoMenezesJr/auto-activities#18]
It would be create to be able to for I'd entering empty workspaces because to me that feels like it breaks the workflow a bit.

**Comment by CleoMenezesJr** [comment]
Thanks. For now I'm out of time, but when I can, I'll take a look.

**Comment by Zetta1Reid0** [comment]
Isn't this handled by Isolate Workspace Option ? If you leave Isolate Workspaces off and you have an open window on your workspace , the overview won't show when you switch workspaces.

**Comment by CleoMenezesJr** [comment]
closed by 409c71fd9eb333f633a6dc1218ac9d44944204a2
