### ISSUE TITLE
Overview not shown, if Mutter 'Hide all Windows' mode is Active.

### ISSUE THREAD

**Issue by Zetta1Reid0** [CleoMenezesJr/auto-activities#22]
Since the Mutter 'Hide all Windows' mode does not hide windows in the the traditional way of hiding them by minimizing everything . Workspace is not actually considered empty and Overview does not show.
This should affect all versions that the mode is implemented that way. But i only tested it on v43.

**Comment by CleoMenezesJr** [comment]
Honestly, I don't think it makes much sense to deal with minimized windows. Better to keep the idea that whether there are windows in the workspaces, regardless of its state.

**Comment by Zetta1Reid0** [comment]
Hmmm . That is true . Well i will close this issue.

**Comment by Zetta1Reid0** [comment]
Well . That is true . Well i closed this anyway since i can't seem to access the variable that the desktop is shown anyway.

**Comment by CleoMenezesJr** [comment]
> Well . That is true . Well i closed this anyway since i can't seem to access the variable that the desktop is shown anyway.

If you find something about it, and it's a good implementation, we could discuss implementing it, but for now I don't see it as a priority.
