### ISSUE TITLE
Error after updating to version 6

### ISSUE THREAD

**Issue by rene-coty** [CleoMenezesJr/auto-activities#24]
I have updated Auto Activities to version 6, but my extension manager now indicates that the extension encoutered a problem and can't be enabled (see screenshots below):
![Capture d’écran du 2023-02-11 10-55-52](https://user-images.githubusercontent.com/95506494/218251895-5cffac67-8bef-41db-8fdf-b25216d1483c.png)
![Capture d’écran du 2023-02-11 10-55-59](https://user-images.githubusercontent.com/95506494/218251891-39320450-2398-4902-846a-a258accb22af.png)

As of the technical details, I got the following report:

The settings of extension auto-activities@CleoMenezesJr.github.io had an error:
```
GLib.FileError: L’ouverture du fichier « /home/ireneethirion/.local/share/gnome-shell/extensions/auto-activities@CleoMenezesJr.github.io/schemas/gschemas.compiled » a échoué : échec de open() : Aucun fichier ou dossier de ce type
```

Stack trace:
```
getSettings@resource:///org/gnome/Shell/Extensions/js/misc/extensionUtils.js:226:31
buildPrefsWidget@/home/ireneethirion/.local/share/gnome-shell/extensions/auto-activities@CleoMenezesJr.github.io/prefs.js:46:33
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:32:44
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I have tried to uninstall & reinstall the extension but I still can't enable it because of this error

**Comment by CleoMenezesJr** [comment]
Could you please remove the extension. Logout and after logging in, install again and let me know if it keeps happening?

**Comment by rene-coty** [comment]
I have tried and it keeps hapening..

**Comment by CleoMenezesJr** [comment]
@rene-coty thanks for reporting. It was my mistake. I had forgotten to upload `schemes.compiled` file. I've already submitted a new version, and right now it should be available to everyone.
