### ISSUE TITLE
Still not working on GNOME 43

### ISSUE THREAD

**Issue by mathricci** [CleoMenezesJr/auto-activities#26]
I'm using GNOME 43.3 on Debian Testing (Bookworm). I know you said the problem will be fixed soon but I'd like to know if it will fix the extension for my GNOME version.

Thank you very much for your incredible extension.

Keep up the good work!

**Comment by CleoMenezesJr** [comment]
> 

Hello! Could you describe exactly the problem? Any log?

**Comment by mathricci** [comment]
When I switch workspaces the extension doesn't work. However when I close a window it works.
Sorry but Idk how to generate any log.

**Comment by mihalycsaba** [comment]
Yeah, I think it should trigger when you switch(ctrl+righ arrow) to an empty workspace.

**Comment by mihalycsaba** [comment]
Oh wait, it works if I uncheck last workspace under ignore.

**Comment by mathricci** [comment]
[Gravação de tela de 2023-03-27 09-48-37.webm](https://user-images.githubusercontent.com/125386969/227944605-27885bf7-8802-43a5-b9c0-d5b6c2b4e8ef.webm)

Here's a video to help you. When I switch workspaces nothing works. However, when I open and then close a window it works properly.

**Comment by CleoMenezesJr** [comment]
> Here's a video to help you. When I switch workspaces nothing works. However, when I open and then close a window it works properly.

Read the [version 18 release log](https://github.com/CleoMenezesJr/auto-activities/releases/tag/v18): _Hide New Window option is enabled by default._
