### ISSUE TITLE
Opening an app on an empty workspace does not gain focus

### ISSUE THREAD

**Issue by anmolmathias** [CleoMenezesJr/auto-activities#29]
Using a keyboard shortcut to open an app on an empty workspace from the overview results in that particular application losing focus. I have to alt-tab that app in order to proceed further. I turned off all other extensions to minimize conflict and it still happens. Using the mouse to launch applications work fine. It's only when an app is launched with a keyboard shortcut that it ceases to gain focus. I also noticed this happens only with GTK apps. Qt apps gain focus correctly.
Occurs on Fedora 38 with Gnome 44.1. Bugs out on both wayland and xorg for me.

I have attached a short screencast that demonstrates this. Notice the loss of focus indicated on the top left of the panel by the activities and applications indicator. Please let me know if you'd like me to try any other scenarios.

[Screencast from 2023-05-15 12-30-35.webm](https://github.com/CleoMenezesJr/auto-activities/assets/15323519/4078ace6-df99-4293-9d2c-b56af12d6509)

**Comment by CleoMenezesJr** [comment]
Thx for report. At first, I also thought it was Auto Activities, but after some testing I confirmed it was a problem with Mutter.
See: https://gitlab.gnome.org/GNOME/mutter/-/issues/2690
