### ISSUE TITLE
Port to GNOME 45

### ISSUE THREAD

**Issue by gregorydk** [CleoMenezesJr/auto-activities#30]
The extension will break with GNOME Shell 45 and needs to be ported.

https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

**Comment by rtqate** [comment]
Arch updated to Gnome 45, and I can confirm that this is exactly the case - not working on 45...

**Comment by CleoMenezesJr** [comment]
The extension has already been ported for a month, I just forgot to upstream it. Sorry guys

**Comment by ferlanero** [comment]
Do you plan to upload it for Gnome 45, please? This is an awesome addon for it.

**Comment by rtqate** [comment]
> The extension has already been ported for a month, I just forgot to upstream it. Sorry guys

Thanks for porting, but I still wish it worked on my system, for some reason :) Shell v. 45 is not available in the dropdown on the Extensions site, and when I try hacking the medatada.json file, to include v. 45 (an old trick that almost always works), the extension still doesn't work after logout/login, and shows the following:
`The settings of extension auto-activities@CleoMenezesJr.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/myUserName/.local/share/gnome-shell/extensions/auto-activities@CleoMenezesJr.github.io/prefs.js:21:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```
`
Grateful, if this could be resolved, thanks!

**Comment by CleoMenezesJr** [comment]
As I already said. The extension has already been ported, I just need to upload it. I'm just making some adjustments. There is no need for worries. Even before GNOME 45 was released, the extension had already been ported, I just need to review a few things and it will be available by this weekend.
