### ISSUE TITLE
Inability to interact with the cursor on the desktop

### ISSUE THREAD

**Issue by nahuelwexd** [CleoMenezesJr/auto-activities#31]
Basically what the title says. Once the extension is activated, when I restart the session, I find that I cannot interact with my desktop using the cursor. Using the keyboard I can interact.

This happens in GNOME Shell 44.4

Attached [screen recording](https://github.com/CleoMenezesJr/auto-activities/assets/18204745/cc83fa16-8b40-4e75-84fb-a5c8789fc014) and screenshot of my settings: ![Screenshot from 2023-09-13 12-09-39](https://github.com/CleoMenezesJr/auto-activities/assets/18204745/c8dfcf46-5467-4f3e-85a5-d9d2fe51386d)

**Comment by CleoMenezesJr** [comment]
Can you reproduce this in version 45?

**Comment by nahuelwexd** [comment]
Once Fedora 39 reaches stable, I'll give it a try.

**Comment by nahuelwexd** [comment]
Fedora 39 came out a while ago, and I've been experimenting with the extension again. The error no longer seems to occur, so I will close the issue.
